development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://gceokqcpspobqe:0236a0eb70e5e770cb37e261d7dbbfad02614f8fc4c48315b8d7e321cb18ad9a@ec2-23-23-244-83.compute-1.amazonaws.com:5432/delj2ocvp5s85i
  channel_prefix: rails_app_production
